app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, nombre, id_categoria=None):
        self.id_categoria = id_categoria
        self.nombre = nombre
        

    def save(self):
        # Create a New Object in DB
        if self.id_categoria is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO category(nombre) VALUES(%s)"
                val = (self.nombre,)
                cursor.execute(sql, val)
                mydb.commit()
                self.id_categoria = cursor.lastrowid
                return self.id_categoria
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE category SET nombre = %s WHERE id_categoria = %s"
                val = (self.nombre, self.id_categoria)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id_categoria
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM category WHERE id_categoria = { self.id_categoria }"
            cursor.execute(sql)
            mydb.commit()
            return self.id_categoria
            
    @staticmethod
    def get(id_categoria):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT nombre FROM category WHERE id_categoria = { id_categoria }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            nombre = Category(result["nombre"], id_categoria)
            return nombre
        
          
    @staticmethod
    def get_all():
        categoria = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT nombre,id_categoria FROM category"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categoria.append(Category(item["nombre"], item["id_categoria"]))
            return categoria
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id_categoria) FROM category"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id_categoria } - { self.nombre }"

app/forms/category_forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CreateCategoryForm(FlaskForm):
    nombre = StringField('Categoria', 
                           validators=[DataRequired()])

    submit = SubmitField('Guardar')

class UpdateCategoryForm(FlaskForm):
    nombre = StringField('Categoria', 
                           validators=[DataRequired()])

    submit = SubmitField('Actualizar')

app/views/category_views.py
from flask import Blueprint, render_template, redirect ,url_for,request,flash
from models.categories import Category

from forms.category_forms import CreateCategoryForm, UpdateCategoryForm
category_view =Blueprint('cat',__name__)

@category_view.route("/categorias/")
def catp():
    category=Category.get_all()
    return render_template("/categories/categories.html",
                            categories=category)

@category_view.route("/crear", methods=('GET','POST'))
def catn():
    form = CreateCategoryForm()
    if form.validate_on_submit():
        nombre= form.nombre.data
        cat = Category(nombre)
        cat.save()
        return redirect(url_for('cat.catp'))
    return render_template("/categories/create_cat.html", form=form)

@category_view.route("/categorias/<int:id_categoria>/editar", methods=('GET','POST'))
def cate(id_categoria):
    form= UpdateCategoryForm()
    cate=Category.get(id_categoria)
    if form.validate_on_submit():
        cate.nombre=form.nombre.data
        cate.save()
        return redirect(url_for('cat.catp'))
    form.nombre.data =cate.nombre
    return render_template("/categories/edit_cat.html", form=form)

@category_view.route('/categories/<int:id_categoria>/delete/', methods =('POST',))
def delete_cat(id_categoria):
    #Obtener Cat desde id
    cat = Category.get(id_categoria)
    cat.delete()
    #Enviar datos a form
    return redirect(url_for('cat.catp'))

app/templates/categories/categorias.html
{%extends 'base.html'%}


{% block title %}
productos
{% endblock %}
{% block content %}
<nav class="titulo"><h1>Categorias</h1></nav>

<a href="{{ url_for('cat.catn') }}" >
    <input type="button" value="Crear nueva categoria" class="bpr bpr-ac">
</a>
<a href="{{ url_for('cat.cate') }}" >
    <input type="button" value="Editar categoria" class="bpr bpr-ed">
</a>

<div class="bloc-cat">
    <div class="cat">
        <img src="" alt="imagen" >
        <div>
            <p class="item">descripcion</p>
            <p class="item">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, ullam incidunt! Velit, quidem eligendi. Eaque reprehenderit dicta iste necessitatibus! Sequi esse soluta sit quam fugit aspernatur perferendis, suscipit quibusdam quidem voluptatibus animi explicabo quo corrupti perspiciatis voluptatem consectetur laudantium iste id consequuntur inventore unde nihil voluptates. Enim officia labore soluta corporis earum, autem a voluptatibus velit sint? Vitae ad voluptate debitis ipsa velit, deleniti blanditiis doloremque aut architecto consequuntur fugiat dolore delectus molestias? Est modi dolore nam autem perferendis excepturi id eveniet voluptates nulla hic odio unde assumenda, soluta officiis, similique sapiente. Quisquam, suscipit impedit. Debitis quis nobis id vel.</p>
        </div>
    </div>
</div>
<div class="bloc-cat">
    <div class="cat">
        <img src="" alt="imagen" >
        <div>
            <p class="item">descripcion</p>
            <p class="item">Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum, ullam incidunt! Velit, quidem eligendi. Eaque reprehenderit dicta iste necessitatibus! Sequi esse soluta sit quam fugit aspernatur perferendis, suscipit quibusdam quidem voluptatibus animi explicabo quo corrupti perspiciatis voluptatem consectetur laudantium iste id consequuntur inventore unde nihil voluptates. Enim officia labore soluta corporis earum, autem a voluptatibus velit sint? Vitae ad voluptate debitis ipsa velit, deleniti blanditiis doloremque aut architecto consequuntur fugiat dolore delectus molestias? Est modi dolore nam autem perferendis excepturi id eveniet voluptates nulla hic odio unde assumenda, soluta officiis, similique sapiente. Quisquam, suscipit impedit. Debitis quis nobis id vel.</p>
        </div>
    </div>
</div>


{% endblock %}

app/templates/categories/categories.html
{% extends 'base.html' %}

{% block title %}
    Categories
{% endblock %}

{% block content %}

<nav class="titulo">
    <h1>
        <a href="{{ url_for('home.cerrar') }}" class="bpr bpr-ed"> Regresar</a>
        Categories Page</h1></nav>

    <h2>Lista de Categorias</h2>
    <a href="{{ url_for('cat.catn') }}" class="bpr bpr-ac">Nueva Categoria</a>
    <nav class="a-table">

        <table id="sale">
            <thead>
            <tr>
                <th>ID</th>
                <th>Nombre</th>
       
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for cat in categories %}
                <tr>
                    <td>{{ cat.id_categoria }}</td>
                    <td>{{ cat.nombre }}</td>
                    <td>
                        <a href="{{ url_for('cat.cate', id_categoria=cat.id_categoria) }}">
                            <i class="fa fa-refresh"></i> 
                        </a> 
                        <form method="post" action="{{ url_for('cat.delete_cat', id_categoria=cat.id_categoria) }}">
                            <button type="submit"
                            onclick="return confirm('¿seguro de borrar este objeto?')" class="fa">
                            <i class="fa fa-trash"></i>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</nav>
{% endblock %}

app/templates/categories/creat_cat.html
{%extends 'base.html'%}


{% block title %}
productos
{% endblock %}

{% block content %}
<nav class="titulo"> Crear nueva categoria </nav>

    <nav class="pdiv">
        <div class="func func-cat">
            <h2>Nombre Categoria</h2>
            <input type="text" class="margin">
        
            <h2> descripcion</h2>
            <input type="text" class="margin">
        </div>
        <a href="{{ url_for('cat.catp') }}"> 

            <input type="button" value="Guardar" class="bpr bpr-ac">
        </a>
        
    </nav>
    

{% endblock content %}

app/templates/categories/create_cat.html
{% extends 'base.html' %}

{% block title %}
    Agregar Categoria
{% endblock %}

{% block content %}
<nav class="titulo"> Añadir categorias </nav>

    <form method="Post" class="pdiv">
        {{ form.csrf_token }}
        <div class="func func-cat">
            {{ form.nombre.label( class="txtlab") }}
            {{ form.nombre(placeholder="Nombre", class="margin") }}
            {% if form.nombre.errors %}
                {% for error in form.nombre.errors %}
                    <p>{{ error }}</p>
                {% endfor %} 
            {% endif %}
        </div>

        <div>
            {{ form.submit(class="bpr bpr-ac") }}
        </div>
    </form>
{% endblock content %}

app/templates/categories/edit_cat.html
{%extends 'base.html'%}


{% block title %}
productos
{% endblock %}

{% block content %}
<nav class="titulo"><h1>
    <a href="{{ url_for('cat.catp') }}" class="bpr bpr-ed"> Regresar</a>
    editar categorias 
</h1>
</nav>


        <form method="Post" class="pdiv">
            {{ form.csrf_token }}
            <div class="func func-cat">
                {{ form.nombre.label( class="txtlab") }}
                {{ form.nombre(placeholder="Nombre", class="margin") }}
                {% if form.nombre.errors %}
                    {% for error in form.nombre.errors %}
                        <p>{{ error }}</p>
                    {% endfor %} 
                {% endif %}
            </div>
    
            <div>
                {{ form.submit(class="bpr bpr-ac") }}
            </div>
        </form>

{% endblock content %}